### ISSUE TITLE
Crash has occurred during alt-tab switching

### ISSUE THREAD

**Issue by ilyuha21st** [ilyuha21st/caffeine-cli#1]
Trace:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/caffeine_cli-1.0.0-py2.7.egg/caffeinecli/app_inst.py", line 71, in check_activity
    if (caffeine.is_fullscreen() and caffeine.wm_class in wm_classes) or \
  File "/usr/local/lib/python2.7/dist-packages/caffeine_cli-1.0.0-py2.7.egg/caffeinecli/caffeine.py", line 84, in is_fullscreen
    self._displ.intern_atom("_NET_WM_STATE"), X.AnyPropertyType)
  File "build/bdist.linux-x86_64/egg/Xlib/xobject/drawable.py", line 472, in get_full_property
    prop = self.get_property(property, property_type, 0, sizehint)
  File "build/bdist.linux-x86_64/egg/Xlib/xobject/drawable.py", line 461, in get_property
    long_length = length)
  File "build/bdist.linux-x86_64/egg/Xlib/protocol/rq.py", line 1360, in __init__
    self.reply()
  File "build/bdist.linux-x86_64/egg/Xlib/protocol/rq.py", line 1380, in reply
    raise self._error
BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x00000000), sequence_number = 1073, major_opcode = 20, minor_opcode = 0 
```

**Comment by ilyuha21st** [comment]
Issue happens during switching X11 context. Fix might be simply ignore such error since user activity has just occurred, and do not care about actual window state.

**Comment by ilyuha21st** [comment]
Fixed
